onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -label clk -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/clk
add wave -noupdate -label pc -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/core/pc
add wave -noupdate -label ins -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/ins
add wave -noupdate -label reset_n -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/reset
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/avm_instructionMaster_waitrequest
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/iCacheStall
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/dCacheStall
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/avm_dCacheADDR_read
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/avm_dCacheADDR_write
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/avm_dCacheADDR_address
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/avm_dCacheADDR_writedata
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/avm_dCacheADDR_readdata
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/avm_dCacheADDR_waitrequest
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/avm_dCacheDATA_write
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/avm_dCacheDATA_address
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/avm_dCacheDATA_writedata
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/avm_dCacheDATA_waitrequest
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/avm_dCacheCtrlTx_write
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/avm_dCacheCtrlTx_address
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/avm_dCacheCtrlTx_writedata
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/avm_dCacheCtrlTx_waitrequest
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/avs_dCacheCtrlRx_write
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/avs_dCacheCtrlRx_writedata
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/avm_instructionMaster_read
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/avm_instructionMaster_address
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/avm_instructionMaster_readdata
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/avm_instructionMaster_waitrequest
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/avm_instructionMaster_readdatavalid
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/avs_debugSlave_write
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/avs_debugSlave_writedata
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/avs_debugSlave_irq
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/memwrite
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/memread
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/mem16
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/mem8
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/memaddress
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/memwritedata
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/memreaddata
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/memCanRead
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/memCanWrite
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/insValid
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/irq
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/irq_number
add wave -noupdate -label clk -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/clk
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/csi_clockreset_clk
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_sdram/clk
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/csi_clockreset_reset_n
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/avs_dCacheDATA_write
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/avs_dCacheDATA_writedata
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/avs_dCacheADDR_read
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/avs_dCacheADDR_write
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/avs_dCacheADDR_writedata
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/avs_dCacheADDR_readdata
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/avm_dCacheCtrlTx_write
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/avm_dCacheCtrlTx_address
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/avm_dCacheCtrlTx_writedata
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/avm_dCacheCtrlTx_waitrequest
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/avs_dCacheCtrlRx_write
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/avs_dCacheCtrlRx_writedata
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/avm_dataMaster_read
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/avm_dataMaster_write
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/avm_dataMaster_address
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/avm_dataMaster_writedata
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/avm_dataMaster_byteenable
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/avm_dataMaster_readdata
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/avm_dataMaster_waitrequest
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/avm_dataMaster_readdatavalid
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/avm_dataMaster_irq
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/fetchDone_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/state_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/cacheWrite_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/cacheData_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/cacheQ_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/cacheQData_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/stall_accel_for_read
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/stall_accel_for_write
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/stall_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/stall_accel_until_fetchDone
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/mem8_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/mem16_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/fetchData_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/memReadData_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/memReadDataWord_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/mem_accelerator
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/irq
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_tiger_top_0/tiger_top_0/irq_number
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/avm_dataMaster_irqnumber
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/cacheClkEn
add wave -noupdate /test_bench/DUT/the_data_cache_0/data_cache_0/csi_clockreset_clk
add wave -noupdate /test_bench/DUT/the_data_cache_0/data_cache_0/csi_clockreset_reset_n
add wave -noupdate /test_bench/DUT/the_data_cache_0/data_cache_0/avs_dCacheDATA_write
add wave -noupdate /test_bench/DUT/the_data_cache_0/data_cache_0/avs_dCacheDATA_writedata
add wave -noupdate /test_bench/DUT/the_data_cache_0/data_cache_0/avs_dCacheADDR_read
add wave -noupdate /test_bench/DUT/the_data_cache_0/data_cache_0/avs_dCacheADDR_write
add wave -noupdate /test_bench/DUT/the_data_cache_0/data_cache_0/avs_dCacheADDR_writedata
add wave -noupdate /test_bench/DUT/the_data_cache_0/data_cache_0/avs_dCacheADDR_readdata
add wave -noupdate /test_bench/DUT/the_data_cache_0/data_cache_0/avm_dCacheCtrlTx_write
add wave -noupdate /test_bench/DUT/the_data_cache_0/data_cache_0/avm_dCacheCtrlTx_address
add wave -noupdate /test_bench/DUT/the_data_cache_0/data_cache_0/avm_dCacheCtrlTx_writedata
add wave -noupdate /test_bench/DUT/the_data_cache_0/data_cache_0/avm_dCacheCtrlTx_waitrequest
add wave -noupdate /test_bench/DUT/the_data_cache_0/data_cache_0/avs_dCacheCtrlRx_write
add wave -noupdate /test_bench/DUT/the_data_cache_0/data_cache_0/avs_dCacheCtrlRx_writedata
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/avs_accelADDR_address
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/avs_accelADDR_begintransfer
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/avs_accelADDR_read
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/avs_accelADDR_write
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/avs_accelADDR_writedata
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/avs_accelADDR_readdata
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/avs_accelADDR_waitrequest
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/avs_accelDATA_begintransfer
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/avs_accelDATA_write
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/avs_accelDATA_writedata
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/avs_accelDATA_waitrequest
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/avs_accelSIZE_begintransfer
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/avs_accelSIZE_write
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/avs_accelSIZE_writedata
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/avs_accelSIZE_waitrequest
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/avm_AccelMaster_read
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/avm_AccelMaster_write
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/avm_AccelMaster_address
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/avm_AccelMaster_writedata
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/avm_AccelMaster_byteenable
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/avm_AccelMaster_readdata
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/avm_AccelMaster_waitrequest
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/avm_AccelMaster_readdatavalid
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/avm_dataMaster_read
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/avm_dataMaster_write
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/avm_dataMaster_address
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/avm_dataMaster_writedata
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/avm_dataMaster_byteenable
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/avm_dataMaster_readdata
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/avm_dataMaster_waitrequest
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/avm_dataMaster_readdatavalid
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/avm_dataMaster_irq
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/avm_dataMaster_irqnumber
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/cacheHit
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/cacheAddress
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/blockWord
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/tag
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/memReadDataWord
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/cacheWrite
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/cacheClkEn
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/cacheData
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/cacheQ
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/cacheTag
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/validBit
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/cacheQData
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/cacheWriteData
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/writeData
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/savedTag
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/savedBlockWord
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/savedByte
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/fetchDone
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/bypassCache
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/address
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/writeDataWord
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/fetchData
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/fetchWord
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/state
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/savedMem16
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/savedMem8
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/flushAddr
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/clk
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/reset_n
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/memRead
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/memWrite
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/memAddress
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/memWriteData
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/memReadData
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/flush
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/mem8
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/mem16
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/canRead
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/canWrite
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/canFlush
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/stall
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/cacheClkEn_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/cacheClkEn_proc
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/memRead_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/memWrite_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/memAddress_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/memWriteData_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/memReadData_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/mem8_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/mem16_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/mem64_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/cacheHit_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/cacheAddress_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/blockWord_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/tag_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/byte_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/memReadDataWord_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/cacheWrite_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/cacheData_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/cacheQ_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/cacheTag_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/validBit_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/cacheQData_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/cacheWriteData_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/writeData_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/savedTag_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/savedBlockWord_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/savedByte_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/fetchDone_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/stall_accel_for_read
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/stall_accel_for_write
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/stall_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/address_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/writeDataWord_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/fetchData_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/fetchWord_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/state_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/savedMem64_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/savedMem16_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/savedMem8_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/flushAddr_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/mem_accelerator
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/stall_cpu_for_accel_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/stall_cpu_for_accel
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/stall_cpu_nodly
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/stall_accel_until_fetchDone
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/write_after_read
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/read_after_write
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/state_64
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/memRead_accel64
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/memWrite_accel64
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/stall_accel_64
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/memRead_64
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/memWrite_64
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/memReadData_accel_lo
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/waitrequest_32
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/counter_64
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_data_cache_0/data_cache_0/stall_condition
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/csi_clockreset_clk
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/csi_clockreset_reset
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/avs_s1_address
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/avs_s1_read
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/avs_s1_write
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/avs_s1_writedata
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/avs_s1_readdata
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/avm_ADDR_readdata
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/avm_ADDR_writedata
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/avm_ADDR_waitrequest
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/avm_ADDR_address
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/avm_ADDR_write
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/avm_ADDR_read
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/avm_DATA_waitrequest
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/avm_SIZE_waitrequest
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/avm_DATA_address
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/avm_DATA_writedata
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/avm_DATA_write
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/avm_SIZE_address
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/avm_SIZE_writedata
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/avm_SIZE_write
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/finish
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/return_val
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_address
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_address
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_enable
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_write_enable
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_waitrequest
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_in
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_out
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_size
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/clk
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/reset
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/start
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/data_from_memory
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/data_to_memory
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/sdram_data
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/sdram_data_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/data_from_memory_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/done
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/read_data_asserted_lo
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/sdram_data_ready
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/flag_to_sdram
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/enable
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/write_enable
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/check_for_sdram
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/BRAM_data_ready
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/BRAM_data_ready_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/sdram_data_ready_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/sdram_data_ready_reg_dly
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/start_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/finish_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_inst/clk
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_inst/memory_controller_address
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_inst/memory_controller_enable
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_inst/memory_controller_write_enable
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_inst/memory_controller_in
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_inst/memory_controller_size
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_inst/memory_controller_out_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_inst/memory_controller_out
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_inst/A_address
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_inst/A_write_enable
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_inst/A_in
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_inst/A_out
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_inst/imem_address
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_inst/imem_write_enable
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_inst/imem_in
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_inst/imem_out
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_inst/outData_address
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_inst/outData_write_enable
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_inst/outData_in
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_inst/outData_out
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_inst/main_bb_nph57_reg_var0_address
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_inst/main_bb_nph57_reg_var0_write_enable
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_inst/main_bb_nph57_reg_var0_in
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_inst/main_bb_nph57_reg_var0_out
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_inst/main_bb_nph57_dmem_address
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_inst/main_bb_nph57_dmem_write_enable
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_inst/main_bb_nph57_dmem_in
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_inst/main_bb_nph57_dmem_out
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_inst/tag
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_inst/prevTag
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_inst/prevAddr
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/memory_controller_inst/prevSize
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/clk
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/reset
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/start
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/finish
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/return_val
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/memory_controller_address
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/memory_controller_enable
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/memory_controller_write_enable
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/memory_controller_waitrequest
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/memory_controller_in
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/memory_controller_size
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/memory_controller_out
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/cur_state
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb_nph57_dmem1
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb_nph57_dmem1_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/legup_memset_4_start
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/legup_memset_4_m
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/legup_memset_4_c
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/legup_memset_4_n
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/legup_memset_4_memory_controller_address
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/legup_memset_4_memory_controller_write_enable
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/legup_memset_4_memory_controller_in
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/legup_memset_4_memory_controller_waitrequest
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/legup_memset_4_memory_controller_enable
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/legup_memset_4_memory_controller_out
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/legup_memset_4_memory_controller_size
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/legup_memset_4_finish
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb_i_056_phi_temp
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb_i_056
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb_scevgep65
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb_var0
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb_var0_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb_scevgep65_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb_exitcond64
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb_exitcond64_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_preheader_var1
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_preheader_scevgep62
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_preheader_scevgep62_1
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_preheader_scevgep62_2
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_preheader_scevgep62_3
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_preheader_scevgep62_4
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_preheader_scevgep62_5
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_preheader_scevgep62_6
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_preheader_scevgep62_7
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_preheader_var2
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_preheader_var3
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_preheader_scevgep62_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_preheader_scevgep62_1_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_preheader_scevgep62_2_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_preheader_scevgep62_3_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_preheader_scevgep62_4_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_preheader_scevgep62_5_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_preheader_scevgep62_6_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_preheader_scevgep62_7_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_pc_0_phi_temp
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_pc_0
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_pc_0_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_Lo_1_phi_temp
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_Lo_1
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_Lo_1_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_Hi_1_phi_temp
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_Hi_1
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_Hi_1_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_var4_phi_temp
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_var4
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_var4_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_var5
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_var6
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_var6_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_var7
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_var7_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_var8
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_var9
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_var9_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_var10
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_var10_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb8_var11
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb8_var12
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb8_var13
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb8_var13_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb8_var14
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb8_var15
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb8_var15_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb8_var16
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb8_var17
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb8_var17_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb8_var18
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb8_var19
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb8_var19_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb9_var20
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb9_var21
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb9_var21_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb9_var22
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb9_var23
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb9_var24
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb9_var24_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb9_var22_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb9_var25
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb9_var25_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb9_var23_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb10_var26
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb10_var27
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb10_var27_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb10_var28
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb10_var29
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb10_var30
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb10_var30_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb10_var28_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb10_var31
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb10_var31_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb10_var29_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb11_var32
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb11_var33
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb11_var33_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb11_var34
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb11_var35
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb11_var35_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb11_var34_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb11_var36
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb11_var36_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb11_var37
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb11_var37_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb11_var38
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb11_var38_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb11_var39
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb11_var39_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb11_var40
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb11_var41
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb11_var41_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb12_var42
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb12_var43
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb12_var43_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb12_var44
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb12_var45
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb12_var45_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb12_var44_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb12_var46
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb12_var46_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb12_var47
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb12_var47_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb12_var48
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb12_var48_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb12_var49
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb12_var49_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb12_var50
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb12_var51
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb12_var51_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb13_var52
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb13_var52_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb14_var53
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb14_var53_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb15_var54
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb15_var55
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb15_var55_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb15_var56
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb15_var57
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb15_var58
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb15_var58_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb15_var56_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb15_var59
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb15_var57_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb16_var60
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb16_var61
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb16_var61_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb16_var62
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb16_var63
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb16_var64
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb16_var64_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb16_var62_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb16_var65
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb16_var63_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb17_var66
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb17_var67
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb17_var67_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb17_var68
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb17_var69
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb17_var70
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb17_var70_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb17_var68_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb17_var71
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb17_var69_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb18_var72
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb18_var73
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb18_var73_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb18_var74
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb18_var75
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb18_var75_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb18_var74_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb19_var76
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb19_var77
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb19_var77_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb19_var78
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb19_var79
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb19_var79_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb19_var78_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb20_var80
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb20_var81
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb20_var81_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb20_var82
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb20_var83
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb20_var84
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb20_var84_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb20_var82_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb20_var85
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb20_var85_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb20_var83_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb21_var86
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb21_var87
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb21_var87_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb21_var88
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb21_var89
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb21_var90
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb21_var90_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb21_var88_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb21_var91
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb21_var91_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb21_var89_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb22_var92
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb22_var93
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb22_var93_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb22_var94
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb22_var95
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb22_var96
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb22_var96_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb22_var94_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb22_var97
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb22_var98
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb22_var95_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb23_var99
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb23_var100
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb23_var100_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb23_var101
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb23_var102
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb23_var103
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb23_var103_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb23_var101_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb23_var104
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb23_var105
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb23_var102_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb24_var106
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb24_var107
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb24_var107_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb26_var108
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb26_var109
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb26_var109_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_preheader_var3_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb27_var110
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb27_var111
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb27_var111_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb28_var112
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb28_var112_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb28_var113
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb28_var114
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb28_var114_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb28_var115
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb28_var116
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb28_var116_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb29_var117
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb29_var118
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb29_var118_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb29_var119
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb29_var119_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb29_var120
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb29_var121
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb29_var121_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb29_var120_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb30_var122
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb30_var123
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb30_var123_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb30_var124
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb30_var124_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb30_var125
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb30_var126
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb30_var125_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb31_var127
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb31_var128
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb31_var128_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb31_var129
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb31_var129_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb31_var130
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb31_var131
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb31_var130_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb32_var132
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb32_var133
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb32_var133_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb32_var134
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb32_var134_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb32_var135
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb32_var136
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb32_var135_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb33_var137
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb33_var138
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb33_var138_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb33_var139
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb33_var140
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb33_var140_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb33_var141
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb33_var142
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb33_var143
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb33_var144
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb33_var144_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb33_var139_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb34_var145
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb34_var146
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb34_var146_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb34_var147
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb34_var148
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb34_var148_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb34_var147_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb34_var149
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb34_var149_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb34_var150
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb34_var151
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb34_var152
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb34_var152_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb35_var153
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb35_var153_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb35_var154
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb35_var154_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb36_var155
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb36_var156
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb36_var156_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb36_var157
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb36_var158
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb36_var158_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb36_var157_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb36_var159
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb36_var159_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb37_var160
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb37_var161
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb37_var161_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb37_var162
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb37_var162_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb38_var163
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb38_var164
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb38_var164_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb38_var165
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb38_var166
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb38_var166_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb38_var165_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb38_var167
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb38_var167_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb39_var168
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb39_var169
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb39_var169_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb39_var170
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb39_var170_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb40_var171
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb40_var172
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb40_var172_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb40_var173
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb40_var173_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb41_var174
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb41_var175
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb41_var175_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb41_var176
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb41_var176_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb42_var177
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb42_var178
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb42_var178_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb42_var179
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb42_var179_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb42_var180
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb42_var181
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb42_var182
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb42_var180_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb43_var183
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb43_var184
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb43_var184_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb43_var185
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb43_var185_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb43_var186
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb43_var187
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb43_var188
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb43_var186_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb7_preheader_var2_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb45_pc_1_phi_temp
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb45_pc_1
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb45_pc_1_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb45_Lo_0_phi_temp
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb45_Lo_0
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb45_Lo_0_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb45_Hi_0_phi_temp
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb45_Hi_0
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb45_Hi_0_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb45_var189
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb45_var189_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb45_var190
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb45_var190_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var191
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var192
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var192_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_scevgep
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_scevgep_1
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var193
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var193_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_scevgep_2
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_scevgep_3
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_scevgep_4
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_scevgep_5
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_scevgep_6
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_scevgep_7
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var194
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var194_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_scevgep_1_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var195
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var196
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var197
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var197_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_scevgep_2_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var198
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var198_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var199
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var200
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var200_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_scevgep_3_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var201
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var202
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var202_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var203
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var204
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var205
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var205_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_scevgep_4_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var206
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var206_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var207
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var208
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var208_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_scevgep_5_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var209
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var210
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var210_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var211
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var212
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var213
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var213_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_scevgep_6_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var214
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var214_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var215
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var216
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var216_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_scevgep_7_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var217
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var218
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var218_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var219
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var220
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var221
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var221_reg
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var222
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var223
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var224
add wave -noupdate -radix hexadecimal /test_bench/DUT/the_main_0/main_0/main_inst/main_bb49_var224_reg
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 8} {1007348317 ps} 1} {{Cursor 5} {676383265 ps} 0}
configure wave -namecolwidth 556
configure wave -valuecolwidth 145
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {673007191 ps} {673233775 ps}
