NAME=aes
SRCS=aes.c
LOCAL_CONFIG = -legup-config=../config.tcl
CFLAG = -g
DEBUGGER = 1
LEVEL = ../../..

NO_OPT = 1
NO_INLINE = 1
DEBUG_KEEP_VARS_IN_MEM = 1

include ../Makefile.common
include $(LEVEL)/Makefile.common
