# +----------------------------------------------------------------------------+
# | License Agreement                                                          |
# |                                                                            |
# | Copyright (c) 1991-2013 Altera Corporation, San Jose, California, USA.     |
# | All rights reserved.                                                       |
# |                                                                            |
# | Any megafunction design, and related net list (encrypted or decrypted),    |
# |  support information, device programming or simulation file, and any other |
# |  associated documentation or information provided by Altera or a partner   |
# |  under Altera's Megafunction Partnership Program may be used only to       |
# |  program PLD devices (but not masked PLD devices) from Altera.  Any other  |
# |  use of such megafunction design, net list, support information, device    |
# |  programming or simulation file, or any other related documentation or     |
# |  information is prohibited for any other purpose, including, but not       |
# |  limited to modification, reverse engineering, de-compiling, or use with   |
# |  any other silicon devices, unless such use is explicitly licensed under   |
# |  a separate agreement with Altera or a megafunction partner.  Title to     |
# |  the intellectual property, including patents, copyrights, trademarks,     |
# |  trade secrets, or maskworks, embodied in any such megafunction design,    |
# |  net list, support information, device programming or simulation file, or  |
# |  any other related documentation or information provided by Altera or a    |
# |  megafunction partner, remains with Altera, the megafunction partner, or   |
# |  their respective licensors.  No other licenses, including any licenses    |
# |  needed under any third party's intellectual property, are provided herein.|
# |  Copying or modifying any file, or portion thereof, to which this notice   |
# |  is attached violates this copyright.                                      |
# |                                                                            |
# | THIS FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR    |
# | IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,   |
# | FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL    |
# | THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER |
# | LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING    |
# | FROM, OUT OF OR IN CONNECTION WITH THIS FILE OR THE USE OR OTHER DEALINGS  |
# | IN THIS FILE.                                                              |
# |                                                                            |
# | This agreement shall be governed in all respects by the laws of the State  |
# |  of California and by the laws of the United States of America.            |
# |                                                                            |
# +----------------------------------------------------------------------------+

# TCL File Generated by Altera University Program
# DO NOT MODIFY

package require -exact qsys 13.1

# +-----------------------------------
# | module altera_up_avalon_video_pll
# | 
set_module_property DESCRIPTION "Creates the required PLL for video clocks on the DE-series boards"
set_module_property NAME altera_up_avalon_video_pll
set_module_property VERSION 13.1
set_module_property GROUP "University Program/Clock"
set_module_property AUTHOR "Altera University Program"
set_module_property DISPLAY_NAME "Video Clocks for DE-series Boards"
set_module_property DATASHEET_URL "../doc/Altera_UP_PLLs.pdf"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property HIDE_FROM_SOPC true
set_module_property EDITABLE false
set_module_property ANALYZE_HDL false
set_module_property VALIDATION_CALLBACK validate
set_module_property COMPOSITION_CALLBACK compose
# | 
# +-----------------------------------


# +-----------------------------------
# | files
# | 
# | 
# +-----------------------------------


# +-----------------------------------
# | parameters
# | 
add_parameter gui_refclk float 50.0
set_parameter_property gui_refclk DISPLAY_NAME "Reference clock"
set_parameter_property gui_refclk GROUP "Input Settings"
set_parameter_property gui_refclk UNITS Megahertz
set_parameter_property gui_refclk AFFECTS_ELABORATION true
set_parameter_property gui_refclk VISIBLE true
set_parameter_property gui_refclk ENABLED true

add_parameter refclk float 50.0
set_parameter_property refclk DISPLAY_NAME "Reference clock"
set_parameter_property refclk GROUP "Input Settings"
set_parameter_property refclk UNITS Megahertz
set_parameter_property refclk AFFECTS_ELABORATION true
set_parameter_property refclk DERIVED true
set_parameter_property refclk VISIBLE false
set_parameter_property refclk ENABLED false

add_parameter video_in_clk_en boolean true
set_parameter_property video_in_clk_en DISPLAY_NAME "Enable Video In clock"
set_parameter_property video_in_clk_en GROUP "Video In Settings"
set_parameter_property video_in_clk_en UNITS None
set_parameter_property video_in_clk_en AFFECTS_ELABORATION true
set_parameter_property video_in_clk_en VISIBLE true
set_parameter_property video_in_clk_en ENABLED true

add_parameter camera string "5MP Digital Camera"
set_parameter_property camera DISPLAY_NAME "Video In Device"
set_parameter_property camera GROUP "Video In Settings"
set_parameter_property camera UNITS None
set_parameter_property camera AFFECTS_ELABORATION true
set_parameter_property camera ALLOWED_RANGES {"5MP Digital Camera"}
set_parameter_property camera VISIBLE true
set_parameter_property camera ENABLED true

#add_parameter device string "VGA Connector"
#set_parameter_property device DISPLAY_NAME "Video Out Device(s)"
#set_parameter_property device GROUP "Video Out Setting"
#set_parameter_property device UNITS None
#set_parameter_property device AFFECTS_ELABORATION true
#set_parameter_property device AFFECTS_GENERATION true
#set_parameter_property device ALLOWED_RANGES {"VGA Connector" "LCD" "Both VGA and LCD"}
#set_parameter_property device VISIBLE true
#set_parameter_property device ENABLED true

add_parameter vga_clk_en boolean true
set_parameter_property vga_clk_en DISPLAY_NAME "Enable VGA clock"
set_parameter_property vga_clk_en GROUP "Video Out Setting"
set_parameter_property vga_clk_en UNITS None
set_parameter_property vga_clk_en AFFECTS_ELABORATION true
set_parameter_property vga_clk_en VISIBLE true
set_parameter_property vga_clk_en ENABLED true

add_parameter gui_resolution string "VGA 640x480"
set_parameter_property gui_resolution DISPLAY_NAME "VGA Resolution"
set_parameter_property gui_resolution GROUP "Video Out Setting"
set_parameter_property gui_resolution UNITS None
set_parameter_property gui_resolution AFFECTS_ELABORATION true
set_parameter_property gui_resolution AFFECTS_GENERATION true
set_parameter_property gui_resolution ALLOWED_RANGES {"VGA 640x480" "SVGA 800x600" "XGA 1024x768" "WXGA 1280x800" "SXGA 1280x1024" "WSXGA 1680x1050" "SDTV 720x480" "HDTV 1280x720"}
set_parameter_property gui_resolution VISIBLE true
set_parameter_property gui_resolution ENABLED true

add_parameter resolution string "VGA 640x480"
set_parameter_property resolution DISPLAY_NAME "VGA Resolution"
set_parameter_property resolution GROUP "Video Out Setting"
set_parameter_property resolution UNITS None
set_parameter_property resolution AFFECTS_ELABORATION true
set_parameter_property resolution AFFECTS_GENERATION true
set_parameter_property resolution ALLOWED_RANGES {"VGA 640x480" "SVGA 800x600" "XGA 1024x768" "WXGA 1280x800" "SXGA 1280x1024" "WSXGA 1680x1050" "SDTV 720x480" "HDTV 1280x720"}
set_parameter_property resolution DERIVED true
set_parameter_property resolution VISIBLE false
set_parameter_property resolution ENABLED false

add_parameter lcd_clk_en boolean true
set_parameter_property lcd_clk_en DISPLAY_NAME "Enable LCD clock"
set_parameter_property lcd_clk_en GROUP "Video Out Setting"
set_parameter_property lcd_clk_en UNITS None
set_parameter_property lcd_clk_en AFFECTS_ELABORATION true
set_parameter_property lcd_clk_en VISIBLE true
set_parameter_property lcd_clk_en ENABLED true

add_parameter lcd string "7\" LCD on VEEK-MT and MTL Module"
set_parameter_property lcd DISPLAY_NAME "LCD Device"
set_parameter_property lcd GROUP "Video Out Setting"
set_parameter_property lcd UNITS None
set_parameter_property lcd AFFECTS_ELABORATION true
set_parameter_property lcd AFFECTS_GENERATION true
set_parameter_property lcd ALLOWED_RANGES {"4.3\" LCD (TRDB_LTM)" "8\" LCD on TPad/VEEK" "7\" LCD on VEEK-MT and MTL Module"}
set_parameter_property lcd VISIBLE true
set_parameter_property lcd ENABLED true

add_parameter device_family string ""
set_parameter_property device_family system_info_type device_family
set_parameter_property device_family VISIBLE false
# | 
# +-----------------------------------


# +-----------------------------------
# | Validation function
# | 
proc validate {} {
	set gui_refclk			[ get_parameter_value "gui_refclk" ]
	set video_in_clk_en	[ get_parameter_value "video_in_clk_en" ]
	set vga_clk_en			[ get_parameter_value "vga_clk_en" ]
	set gui_resolution	[ get_parameter_value "gui_resolution" ]
	set lcd_clk_en			[ get_parameter_value "lcd_clk_en" ]
	set device_family		[ get_parameter_value "device_family" ]
	
	set_parameter_property camera ENABLED false
	set_parameter_property resolution ENABLED false
	set_parameter_property lcd ENABLED false

	if { $video_in_clk_en } {
		set_parameter_property camera ENABLED true
	}
	if { $vga_clk_en } {
		set_parameter_property resolution ENABLED true
	}
	if { $lcd_clk_en } {
		set_parameter_property lcd ENABLED true
	}

	set_parameter_property gui_refclk VISIBLE false
	set_parameter_property refclk VISIBLE false
	set_parameter_property gui_resolution VISIBLE false
	set_parameter_property resolution VISIBLE false

	if {  [ string match -nocase "Cyclone IV*" $device_family ]  || 
			[ string match -nocase "Cyclone III*" $device_family ] ||
			[ string match -nocase "Arria II*" $device_family ] ||
			[ string match -nocase "Stratix III*" $device_family ] ||
			[ string match -nocase "Stratix IV*" $device_family ]} {
		set_parameter_property refclk VISIBLE true
		set_parameter_value refclk 50.0
		
		set_parameter_property resolution VISIBLE true
		set_parameter_value resolution "VGA 640x480"
		
	} else {
		set_parameter_property gui_refclk VISIBLE true
		set_parameter_value refclk $gui_refclk
		
		set_parameter_property gui_resolution VISIBLE true
		set_parameter_value resolution $gui_resolution
	}
}
# | 
# +-----------------------------------


# +-----------------------------------
# | Composition function
# | 
proc compose {} {
	set refclk				[ get_parameter_value "refclk" ]
	set video_in_clk_en	[ get_parameter_value "video_in_clk_en" ]
	set camera				[ get_parameter_value "camera" ]
	set vga_clk_en			[ get_parameter_value "vga_clk_en" ]
	set resolution			[ get_parameter_value "resolution" ]
	set lcd_clk_en			[ get_parameter_value "lcd_clk_en" ]
	set lcd					[ get_parameter_value "lcd" ]
	set device_family		[ get_parameter_value "device_family" ]

	
	# +-----------------------------------
	# | Get required clock frequencies
	# | 
	set required_vga_freq	25.0
	set required_lcd_freq	25.0

	if { $resolution == "SVGA 800x600" } {
		set required_vga_freq	40.0
	} elseif { $resolution == "XGA 1024x768" } {
		set required_vga_freq	65.0
	} elseif { $resolution == "WXGA 1280x800" } {
		set required_vga_freq	83.46
	} elseif { $resolution == "SXGA 1280x1024" } {
		set required_vga_freq	108.0
	} elseif { $resolution == "WSXGA 1680x1050" } {
		set required_vga_freq	147.14
	} elseif { $resolution == "SDTV 720x480" } {
		set required_vga_freq	27.7
	} elseif { $resolution == "HDTV 1280x720" } {
		set required_vga_freq	74.2
	}

	if { $lcd == "8\" LCD on TPad/VEEK" } {
		set required_lcd_freq	40.0
	} elseif { $lcd == "7\" LCD on VEEK-MT and MTL Module" } {
		set required_lcd_freq	33.0
	}
	# | 
	# +-----------------------------------
set device "Both VGA and LCD"

	# +-----------------------------------
	# | add instances
	# |
	if {  [ string match -nocase "Cyclone IV*" $device_family ]  ||
			[ string match -nocase "Cyclone III*" $device_family ] ||
			[ string match -nocase "Arria II*" $device_family ] ||
			[ string match -nocase "Stratix III*" $device_family ] ||
			[ string match -nocase "Stratix IV*" $device_family ]} {
		add_instance video_pll altera_up_altpll
		set_instance_property audio_pll SUPPRESS_ALL_INFO_MESSAGES true
		set_instance_property audio_pll SUPPRESS_ALL_WARNINGS true

		set_instance_parameter_value video_pll type "Video"
		set_instance_parameter_value video_pll video_out $lcd
		
	} else {
		add_instance video_pll altera_pll
		set_instance_property video_pll SUPPRESS_ALL_INFO_MESSAGES true
		set_instance_property video_pll SUPPRESS_ALL_WARNINGS true

		set_instance_parameter_value video_pll gui_reference_clock_frequency $refclk

		set_instance_parameter_value video_pll gui_number_of_clocks 3
		set_instance_parameter_value video_pll gui_output_clock_frequency0 "25.0"
		set_instance_parameter_value video_pll gui_output_clock_frequency1 $required_vga_freq
		set_instance_parameter_value video_pll gui_output_clock_frequency2 $required_lcd_freq
	}

	add_instance reset_from_locked altera_up_avalon_reset_from_locked_signal
	# | 
	# +-----------------------------------


	# +-----------------------------------
	# | add connection points
	# | 
	add_interface ref_clk clock end
	add_interface ref_reset reset end
	if { $video_in_clk_en } {
		add_interface video_in_clk clock start
	}
	if { $vga_clk_en } {
		add_interface vga_clk clock start
	}
	if { $lcd_clk_en } {
		add_interface lcd_clk clock start
	}
	add_interface reset_source reset start

	set_interface_property ref_clk EXPORT_OF "video_pll.refclk"
	set_interface_property ref_reset EXPORT_OF "video_pll.reset"

	if { $video_in_clk_en } {
		set_interface_property video_in_clk EXPORT_OF "video_pll.outclk0"
	}
	if { $vga_clk_en } {
		set_interface_property vga_clk EXPORT_OF "video_pll.outclk1"
	}
	if { $lcd_clk_en } {
		set_interface_property lcd_clk EXPORT_OF "video_pll.outclk2"
	}
	
	set_interface_property reset_source EXPORT_OF "reset_from_locked.reset_source"

	add_connection "video_pll.locked" "reset_from_locked.locked"
	# | 
	# +-----------------------------------
}
# | 
# +-----------------------------------

