# +----------------------------------------------------------------------------+
# | License Agreement                                                          |
# |                                                                            |
# | Copyright (c) 1991-2013 Altera Corporation, San Jose, California, USA.     |
# | All rights reserved.                                                       |
# |                                                                            |
# | Any megafunction design, and related net list (encrypted or decrypted),    |
# |  support information, device programming or simulation file, and any other |
# |  associated documentation or information provided by Altera or a partner   |
# |  under Altera's Megafunction Partnership Program may be used only to       |
# |  program PLD devices (but not masked PLD devices) from Altera.  Any other  |
# |  use of such megafunction design, net list, support information, device    |
# |  programming or simulation file, or any other related documentation or     |
# |  information is prohibited for any other purpose, including, but not       |
# |  limited to modification, reverse engineering, de-compiling, or use with   |
# |  any other silicon devices, unless such use is explicitly licensed under   |
# |  a separate agreement with Altera or a megafunction partner.  Title to     |
# |  the intellectual property, including patents, copyrights, trademarks,     |
# |  trade secrets, or maskworks, embodied in any such megafunction design,    |
# |  net list, support information, device programming or simulation file, or  |
# |  any other related documentation or information provided by Altera or a    |
# |  megafunction partner, remains with Altera, the megafunction partner, or   |
# |  their respective licensors.  No other licenses, including any licenses    |
# |  needed under any third party's intellectual property, are provided herein.|
# |  Copying or modifying any file, or portion thereof, to which this notice   |
# |  is attached violates this copyright.                                      |
# |                                                                            |
# | THIS FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR    |
# | IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,   |
# | FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL    |
# | THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER |
# | LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING    |
# | FROM, OUT OF OR IN CONNECTION WITH THIS FILE OR THE USE OR OTHER DEALINGS  |
# | IN THIS FILE.                                                              |
# |                                                                            |
# | This agreement shall be governed in all respects by the laws of the State  |
# |  of California and by the laws of the United States of America.            |
# |                                                                            |
# +----------------------------------------------------------------------------+

# TCL File Generated by Altera University Program
# DO NOT MODIFY

package require -exact qsys 13.1

# +-----------------------------------
# | module altera_up_altpll
# | 
set_module_property DESCRIPTION "Creates required PLLs for Cyclone III and Cyclone IV DE-series board peripherals"
set_module_property NAME altera_up_altpll
set_module_property VERSION 13.1
set_module_property GROUP "University Program/Clock"
set_module_property AUTHOR "Altera University Program"
set_module_property DISPLAY_NAME "ALTPLLs for DE-series Board Peripherals"
#set_module_property DATASHEET_URL "doc/Altera_UP_Clocks.pdf"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property HIDE_FROM_SOPC true
set_module_property EDITABLE false
set_module_property ANALYZE_HDL false
set_module_property INTERNAL true
set_module_property VALIDATION_CALLBACK validate
# | 
# +-----------------------------------


# +-----------------------------------
# | files
# | 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL altera_up_altpll
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file altera_up_altpll.v VERILOG PATH hdl/altera_up_altpll.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL altera_up_altpll
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file altera_up_altpll.v VERILOG PATH hdl/altera_up_altpll.v

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL altera_up_altpll
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file altera_up_altpll.v VERILOG PATH hdl/altera_up_altpll.v
# | 
# +-----------------------------------


# +-----------------------------------
# | parameters
# | 
add_display_item "" subcomponent_text text "<html><b>Note</b>: Do not use this component directly. It should only be used by other components in the QSys System Integration Tool or the MegaWizard Plug-In manager.</html>"

add_parameter type string "System/SDRAM"
set_parameter_property type DISPLAY_NAME "Type"
set_parameter_property type GROUP "Settings"
set_parameter_property type UNITS None
set_parameter_property type AFFECTS_VALIDATION true
set_parameter_property type AFFECTS_ELABORATION false
set_parameter_property type AFFECTS_GENERATION false
set_parameter_property type ALLOWED_RANGES {"System/SDRAM" "Video" "Audio"}
set_parameter_property type VISIBLE true
set_parameter_property type ENABLED true

add_parameter video_out string "4.3\" LCD (TRDB_LTM)"
set_parameter_property video_out DISPLAY_NAME "Video Out"
set_parameter_property video_out GROUP "Settings"
set_parameter_property video_out UNITS None
set_parameter_property video_out AFFECTS_VALIDATION true
set_parameter_property video_out AFFECTS_ELABORATION false
set_parameter_property video_out AFFECTS_GENERATION false
set_parameter_property video_out ALLOWED_RANGES {"4.3\" LCD (TRDB_LTM)" "8\" LCD on TPad/VEEK" "7\" LCD on VEEK-MT and MTL Module"}
set_parameter_property video_out VISIBLE true
set_parameter_property video_out ENABLED true

add_parameter audio_clk_freq float 12.288
set_parameter_property audio_clk_freq DISPLAY_NAME "Audio Clock Frequency"
set_parameter_property audio_clk_freq GROUP "Settings"
set_parameter_property audio_clk_freq UNITS Megahertz
set_parameter_property audio_clk_freq AFFECTS_VALIDATION true
set_parameter_property audio_clk_freq AFFECTS_ELABORATION false
set_parameter_property audio_clk_freq AFFECTS_GENERATION false
set_parameter_property audio_clk_freq ALLOWED_RANGES {18.432 16.9344 12.288 12.0 11.2896}
set_parameter_property audio_clk_freq VISIBLE true
set_parameter_property audio_clk_freq ENABLED true

add_parameter gui_device_family string ""
set_parameter_property gui_device_family system_info_type device_family
set_parameter_property gui_device_family VISIBLE false

add_parameter OUTCLK0_MULT integer 1
set_parameter_property OUTCLK0_MULT HDL_PARAMETER true
set_parameter_property OUTCLK0_MULT DERIVED true
set_parameter_property OUTCLK0_MULT VISIBLE false

add_parameter OUTCLK0_DIV integer 1
set_parameter_property OUTCLK0_DIV HDL_PARAMETER true
set_parameter_property OUTCLK0_DIV DERIVED true
set_parameter_property OUTCLK0_DIV VISIBLE false

add_parameter OUTCLK1_MULT integer 1
set_parameter_property OUTCLK1_MULT HDL_PARAMETER true
set_parameter_property OUTCLK1_MULT DERIVED true
set_parameter_property OUTCLK1_MULT VISIBLE false

add_parameter OUTCLK1_DIV integer 1
set_parameter_property OUTCLK1_DIV HDL_PARAMETER true
set_parameter_property OUTCLK1_DIV DERIVED true
set_parameter_property OUTCLK1_DIV VISIBLE false

add_parameter OUTCLK2_MULT integer 1
set_parameter_property OUTCLK2_MULT HDL_PARAMETER true
set_parameter_property OUTCLK2_MULT DERIVED true
set_parameter_property OUTCLK2_MULT VISIBLE false

add_parameter OUTCLK2_DIV integer 1
set_parameter_property OUTCLK2_DIV HDL_PARAMETER true
set_parameter_property OUTCLK2_DIV DERIVED true
set_parameter_property OUTCLK2_DIV VISIBLE false

add_parameter PHASE_SHIFT INTEGER 0
set_parameter_property PHASE_SHIFT HDL_PARAMETER true
set_parameter_property PHASE_SHIFT DERIVED true
set_parameter_property PHASE_SHIFT VISIBLE false

add_parameter DEVICE_FAMILY STRING "Cyclone IV"
set_parameter_property DEVICE_FAMILY HDL_PARAMETER true
set_parameter_property DEVICE_FAMILY DERIVED true
set_parameter_property DEVICE_FAMILY VISIBLE false
# | 
# +-----------------------------------


# +-----------------------------------
# | connection point refclk
# | 
add_interface refclk clock end

add_interface_port refclk refclk clk Input 1
# | 
# +-----------------------------------


# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock "refclk"

add_interface_port reset reset reset Input 1
# | 
# +-----------------------------------


# +-----------------------------------
# | connection point locked
# | 
add_interface locked conduit end
set_interface_property locked associatedClock ""
set_interface_property locked associatedReset ""
set_interface_property locked ENABLED true
set_interface_property locked EXPORT_OF ""
set_interface_property locked PORT_NAME_MAP ""
set_interface_property locked CMSIS_SVD_VARIABLES ""
set_interface_property locked SVD_ADDRESS_GROUP ""

add_interface_port locked locked export Output 1
# | 
# +-----------------------------------


# +-----------------------------------
# | connection point outclk0
# | 
add_interface outclk0 clock start

add_interface_port outclk0 outclk0 clk Output 1
# | 
# +-----------------------------------


# +-----------------------------------
# | connection point outclk1
# | 
add_interface outclk1 clock start

add_interface_port outclk1 outclk1 clk Output 1
# | 
# +-----------------------------------


# +-----------------------------------
# | connection point outclk2
# | 
add_interface outclk2 clock start

add_interface_port outclk2 outclk2 clk Output 1
# | 
# +-----------------------------------


# +-----------------------------------
# | Validation function
# | 
proc validate {} {
#	set num_clocks		[ get_parameter_value "num_clocks" ]
	set type						[ get_parameter_value "type" ]
	set video_out				[ get_parameter_value "video_out" ]
	set audio_clk_freq		[ get_parameter_value "audio_clk_freq" ]
	set gui_device_family	[ get_parameter_value "gui_device_family" ]

	set_parameter_value "OUTCLK0_MULT" 1
	set_parameter_value "OUTCLK0_DIV" 1
	set_parameter_value "OUTCLK1_MULT" 1
	set_parameter_value "OUTCLK1_DIV" 1
	set_parameter_value "OUTCLK2_MULT" 1
	set_parameter_value "OUTCLK2_DIV" 1

	set_parameter_value "PHASE_SHIFT" 0
	set_parameter_value "DEVICE_FAMILY" "Cyclone IV"

	if { $type == "Video" } {
		set_parameter_value "OUTCLK0_MULT" 1
		set_parameter_value "OUTCLK0_DIV" 2
		set_parameter_value "OUTCLK1_MULT" 1
		set_parameter_value "OUTCLK1_DIV" 2
		set_parameter_value "OUTCLK2_MULT" 1
		set_parameter_value "OUTCLK2_DIV" 2
		if { $video_out == "8\" LCD on TPad/VEEK" } {
			set_parameter_value "OUTCLK2_MULT" 4
			set_parameter_value "OUTCLK2_DIV" 5
		} elseif { $video_out == "7\" LCD on VEEK-MT and MTL Module" } {
			set_parameter_value "OUTCLK2_MULT" 2
			set_parameter_value "OUTCLK2_DIV" 3
		}
		
	} elseif { $type == "Audio" } {
		if { $audio_clk_freq == 18.432} {
			set_parameter_value "OUTCLK0_MULT" 80
			set_parameter_value "OUTCLK0_DIV" 217

		} elseif { $audio_clk_freq == 16.9344} {
			set_parameter_value "OUTCLK0_MULT" 21
			set_parameter_value "OUTCLK0_DIV" 62

		} elseif { $audio_clk_freq == 12.288} {
			set_parameter_value "OUTCLK0_MULT" 73
			set_parameter_value "OUTCLK0_DIV" 297

		} elseif { $audio_clk_freq == 12.0} {
			set_parameter_value "OUTCLK0_MULT" 6
			set_parameter_value "OUTCLK0_DIV" 25

		} else {
			set_parameter_value "OUTCLK0_MULT" 7
			set_parameter_value "OUTCLK0_DIV" 31
		}

	} else {
		set_parameter_value "PHASE_SHIFT" -3000
	}
	

	# Check Device Family
	if {  [ string match -nocase "Cyclone III*" $gui_device_family ] } {
		set_parameter_value "DEVICE_FAMILY" "Cyclone III"

	} elseif { [ string match -nocase "Cyclone IV*" $gui_device_family ] } {
		set_parameter_value "DEVICE_FAMILY" "Cyclone IV"

	} elseif { [ string match -nocase "Arria II*" $gui_device_family ] } {
		set_parameter_value "DEVICE_FAMILY" "Arria II"

	} elseif { [ string match -nocase "Stratix III*" $gui_device_family ] } {
		set_parameter_value "DEVICE_FAMILY" "Stratix III"

	} else {
		set_parameter_value "DEVICE_FAMILY" "Stratix IV"
	}
}
# | 
# +-----------------------------------


