# TCL File Generated by Component Editor 9.0sp2
# Wed Mar 10 11:34:12 EST 2010
# DO NOT MODIFY


# +-----------------------------------
# | 
# | tiger_top "tiger_top" v1.0
# | null 2010.03.10.11:34:12
# | 
# | 
# | C:/altera/tiger/tiger_mips/tiger_top.v
# | 
# |    ./tiger_top.v syn
# | 
# +-----------------------------------


# +-----------------------------------
# | module tiger_top
# | 
set_module_property DESCRIPTION ""
set_module_property NAME tiger_top
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP CPUs
set_module_property DISPLAY_NAME tiger_top
set_module_property TOP_LEVEL_HDL_FILE tiger_top.v
set_module_property TOP_LEVEL_HDL_MODULE tiger_top
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file tiger_top.v SYNTHESIS
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point global_signals_clock
# | 
add_interface global_signals_clock clock end
set_interface_property global_signals_clock ptfSchematicName ""

set_interface_property global_signals_clock ENABLED true

add_interface_port global_signals_clock clk clk Input 1
add_interface_port global_signals_clock reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point dataMaster
# | 
add_interface dataMaster avalon start
set_interface_property dataMaster adaptsTo ""
set_interface_property dataMaster burstOnBurstBoundariesOnly false
set_interface_property dataMaster doStreamReads false
set_interface_property dataMaster doStreamWrites false
set_interface_property dataMaster linewrapBursts false

set_interface_property dataMaster ASSOCIATED_CLOCK global_signals_clock
set_interface_property dataMaster ENABLED true

add_interface_port dataMaster avm_dataMaster_read read Output 1
add_interface_port dataMaster avm_dataMaster_write write Output 1
add_interface_port dataMaster avm_dataMaster_address address Output 32
add_interface_port dataMaster avm_dataMaster_writedata writedata Output 32
add_interface_port dataMaster avm_dataMaster_byteenable byteenable Output 4
add_interface_port dataMaster avm_dataMaster_readdata readdata Input 32
add_interface_port dataMaster avm_dataMaster_waitrequest waitrequest Input 1
add_interface_port dataMaster avm_dataMaster_readdatavalid readdatavalid Input 1
add_interface_port dataMaster avm_dataMaster_irqnumber irqnumber Input 6
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point dataMaster_irq
# | 
add_interface dataMaster_irq interrupt start
set_interface_property dataMaster_irq associatedAddressablePoint dataMaster
set_interface_property dataMaster_irq irqScheme INDIVIDUAL_REQUESTS

set_interface_property dataMaster_irq ASSOCIATED_CLOCK global_signals_clock
set_interface_property dataMaster_irq ENABLED true

add_interface_port dataMaster_irq avm_dataMaster_irq irq Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point instructionMaster
# | 
add_interface instructionMaster avalon start
set_interface_property instructionMaster adaptsTo ""
set_interface_property instructionMaster burstOnBurstBoundariesOnly false
set_interface_property instructionMaster doStreamReads false
set_interface_property instructionMaster doStreamWrites false
set_interface_property instructionMaster linewrapBursts false

set_interface_property instructionMaster ASSOCIATED_CLOCK global_signals_clock
set_interface_property instructionMaster ENABLED true

add_interface_port instructionMaster avm_instructionMaster_read read Output 1
add_interface_port instructionMaster avm_instructionMaster_address address Output 32
add_interface_port instructionMaster avm_instructionMaster_readdata readdata Input 32
add_interface_port instructionMaster avm_instructionMaster_waitrequest waitrequest Input 1
add_interface_port instructionMaster avm_instructionMaster_readdatavalid readdatavalid Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point debugSlave
# | 
add_interface debugSlave avalon end
set_interface_property debugSlave addressAlignment NATIVE
set_interface_property debugSlave bridgesToMaster ""
set_interface_property debugSlave burstOnBurstBoundariesOnly false
set_interface_property debugSlave holdTime 0
set_interface_property debugSlave isMemoryDevice false
set_interface_property debugSlave isNonVolatileStorage false
set_interface_property debugSlave linewrapBursts false
set_interface_property debugSlave maximumPendingReadTransactions 0
set_interface_property debugSlave printableDevice false
set_interface_property debugSlave readLatency 0
set_interface_property debugSlave readWaitTime 1
set_interface_property debugSlave setupTime 0
set_interface_property debugSlave timingUnits Cycles
set_interface_property debugSlave writeWaitStates 1
set_interface_property debugSlave writeWaitTime 1

set_interface_property debugSlave ASSOCIATED_CLOCK global_signals_clock
set_interface_property debugSlave ENABLED true

add_interface_port debugSlave avs_debugSlave_write write Input 1
add_interface_port debugSlave avs_debugSlave_writedata writedata Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point debugSlave_irq
# | 
add_interface debugSlave_irq interrupt end
set_interface_property debugSlave_irq associatedAddressablePoint debugSlave

set_interface_property debugSlave_irq ASSOCIATED_CLOCK global_signals_clock
set_interface_property debugSlave_irq ENABLED true

add_interface_port debugSlave_irq avs_debugSlave_irq irq Output 1
# | 
# +-----------------------------------
