# TCL File Generated by Component Editor on: 
# Wed Aug 22 11:31:37 BST 2007
# DO NOT MODIFY

set_source_file "vJTAGUart.v"
set_module "vJTAGUart"
set_module_description ""
set_module_property instantiateInSystemModule true
set_module_property version "1.0"
set_module_property group "JTAG"
set_module_property editable true

# Module parameters

# Clock Interface global_signals_clock
add_clock_interface "global_signals_clock" 
set_interface_property "global_signals_clock" "externallyDriven" "false"
set_interface_property "global_signals_clock" "clockRateKnown" "false"
set_interface_property "global_signals_clock" "clockRate" "0"
# Ports in interface global_signals_clock
add_port_to_interface "global_signals_clock" "clk" "clk"
add_port_to_interface "global_signals_clock" "reset_n" "reset_n"

# Interface controlSlave
add_interface "controlSlave" "avalon" "slave" "global_signals_clock"
set_interface_property "controlSlave" "isNonVolatileStorage" "false"
set_interface_property "controlSlave" "burstOnBurstBoundariesOnly" "false"
set_interface_property "controlSlave" "transparentBridge" "false"
set_interface_property "controlSlave" "readLatency" "0"
set_interface_property "controlSlave" "readWaitStates" "0"
set_interface_property "controlSlave" "isFlash" "false"
set_interface_property "controlSlave" "holdTime" "0"
set_interface_property "controlSlave" "printableDevice" "false"
set_interface_property "controlSlave" "registerIncomingSignals" "false"
set_interface_property "controlSlave" "readWaitTime" "0"
set_interface_property "controlSlave" "setupTime" "0"
set_interface_property "controlSlave" "addressGroup" "0"
set_interface_property "controlSlave" "interleaveBursts" "false"
set_interface_property "controlSlave" "addressAlignment" "NATIVE"
set_interface_property "controlSlave" "isBigEndian" "false"
set_interface_property "controlSlave" "writeLatency" "0"
set_interface_property "controlSlave" "writeWaitTime" "0"
set_interface_property "controlSlave" "timingUnits" "Cycles"
set_interface_property "controlSlave" "minimumUninterruptedRunLength" "1"
set_interface_property "controlSlave" "registerOutgoingSignals" "false"
set_interface_property "controlSlave" "addressSpan" "2"
set_interface_property "controlSlave" "isMemoryDevice" "false"
set_interface_property "controlSlave" "linewrapBursts" "false"
set_interface_property "controlSlave" "alwaysBurstMaxBurst" "false"
set_interface_property "controlSlave" "writeWaitStates" "0"
set_interface_property "controlSlave" "maximumPendingReadTransactions" "0"
set_interface_property "controlSlave" "wellBehavedWaitrequest" "false"
# Ports in interface controlSlave
add_port_to_interface "controlSlave" "avs_controlSlave_read" "read"
add_port_to_interface "controlSlave" "avs_controlSlave_write" "write"
add_port_to_interface "controlSlave" "avs_controlSlave_readdata" "readdata"
add_port_to_interface "controlSlave" "avs_controlSlave_writedata" "writedata"
add_port_to_interface "controlSlave" "avs_controlSlave_address" "address"
