NAME=dfdiv_dwarv
SRCS=dfdiv_dwarv.c
#UNROLL = -unroll-allow-partial -unroll-threshold=5000
#CFLAG += -mllvm -inline-threshold=10000
LOCAL_CONFIG = -legup-config=config.tcl
LEVEL = ../..

include $(LEVEL)/Makefile.common
