# +----------------------------------------------------------------------------+
# | License Agreement                                                          |
# |                                                                            |
# | Copyright (c) 1991-2013 Altera Corporation, San Jose, California, USA.     |
# | All rights reserved.                                                       |
# |                                                                            |
# | Any megafunction design, and related net list (encrypted or decrypted),    |
# |  support information, device programming or simulation file, and any other |
# |  associated documentation or information provided by Altera or a partner   |
# |  under Altera's Megafunction Partnership Program may be used only to       |
# |  program PLD devices (but not masked PLD devices) from Altera.  Any other  |
# |  use of such megafunction design, net list, support information, device    |
# |  programming or simulation file, or any other related documentation or     |
# |  information is prohibited for any other purpose, including, but not       |
# |  limited to modification, reverse engineering, de-compiling, or use with   |
# |  any other silicon devices, unless such use is explicitly licensed under   |
# |  a separate agreement with Altera or a megafunction partner.  Title to     |
# |  the intellectual property, including patents, copyrights, trademarks,     |
# |  trade secrets, or maskworks, embodied in any such megafunction design,    |
# |  net list, support information, device programming or simulation file, or  |
# |  any other related documentation or information provided by Altera or a    |
# |  megafunction partner, remains with Altera, the megafunction partner, or   |
# |  their respective licensors.  No other licenses, including any licenses    |
# |  needed under any third party's intellectual property, are provided herein.|
# |  Copying or modifying any file, or portion thereof, to which this notice   |
# |  is attached violates this copyright.                                      |
# |                                                                            |
# | THIS FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR    |
# | IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,   |
# | FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL    |
# | THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER |
# | LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING    |
# | FROM, OUT OF OR IN CONNECTION WITH THIS FILE OR THE USE OR OTHER DEALINGS  |
# | IN THIS FILE.                                                              |
# |                                                                            |
# | This agreement shall be governed in all respects by the laws of the State  |
# |  of California and by the laws of the United States of America.            |
# |                                                                            |
# +----------------------------------------------------------------------------+

# TCL File Generated by Altera University Program
# DO NOT MODIFY

package require -exact qsys 13.1

# +-----------------------------------
# | module altera_up_avalon_sys_sdram_pll
# | 
set_module_property DESCRIPTION "Creates the required PLL for system and SDRAM clocks on the DE-series boards"
set_module_property NAME altera_up_avalon_sys_sdram_pll
set_module_property VERSION 13.1
set_module_property GROUP "University Program/Clock"
set_module_property AUTHOR "Altera University Program"
set_module_property DISPLAY_NAME "System and SDRAM Clocks for DE-series Boards"
set_module_property DATASHEET_URL "../doc/Altera_UP_PLLs.pdf"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property HIDE_FROM_SOPC true
set_module_property EDITABLE false
set_module_property ANALYZE_HDL false
set_module_property VALIDATION_CALLBACK validate
set_module_property COMPOSITION_CALLBACK compose
# | 
# +-----------------------------------


# +-----------------------------------
# | files
# | 
# | 
# +-----------------------------------


# +-----------------------------------
# | parameters
# | 
add_parameter gui_refclk float 50.0
set_parameter_property gui_refclk DISPLAY_NAME "Reference clock"
set_parameter_property gui_refclk GROUP "Settings"
set_parameter_property gui_refclk UNITS Megahertz
set_parameter_property gui_refclk AFFECTS_ELABORATION true
set_parameter_property gui_refclk VISIBLE true
set_parameter_property gui_refclk ENABLED true

add_parameter refclk float 50.0
set_parameter_property refclk DISPLAY_NAME "Reference clock"
set_parameter_property refclk GROUP "Settings"
set_parameter_property refclk UNITS Megahertz
set_parameter_property refclk AFFECTS_ELABORATION true
set_parameter_property refclk DERIVED true
set_parameter_property refclk VISIBLE false
set_parameter_property refclk ENABLED false

add_parameter gui_outclk float 50.0
set_parameter_property gui_outclk DISPLAY_NAME "Desired System clock"
set_parameter_property gui_outclk GROUP "Settings"
set_parameter_property gui_outclk UNITS Megahertz
set_parameter_property gui_outclk AFFECTS_ELABORATION true
set_parameter_property gui_outclk VISIBLE true
set_parameter_property gui_outclk ENABLED true

add_parameter outclk float 50.0
set_parameter_property outclk DISPLAY_NAME "Desired System clock"
set_parameter_property outclk GROUP "Settings"
set_parameter_property outclk UNITS Megahertz
set_parameter_property outclk AFFECTS_ELABORATION true
set_parameter_property outclk DERIVED true
set_parameter_property outclk VISIBLE false
set_parameter_property outclk ENABLED false

add_parameter CIII_boards string "DE0"
set_parameter_property CIII_boards DISPLAY_NAME "DE-Series Board"
set_parameter_property CIII_boards GROUP "Settings"
set_parameter_property CIII_boards UNITS None
set_parameter_property CIII_boards AFFECTS_ELABORATION true
set_parameter_property CIII_boards AFFECTS_GENERATION true
set_parameter_property CIII_boards ALLOWED_RANGES {"DE0"}
set_parameter_property CIII_boards VISIBLE false
set_parameter_property CIII_boards ENABLED true

add_parameter CIV_boards string "DE2-115"
set_parameter_property CIV_boards DISPLAY_NAME "DE-Series Board"
set_parameter_property CIV_boards GROUP "Settings"
set_parameter_property CIV_boards UNITS None
set_parameter_property CIV_boards AFFECTS_ELABORATION true
set_parameter_property CIV_boards AFFECTS_GENERATION true
set_parameter_property CIV_boards ALLOWED_RANGES {"DE0-Nano" "DE2-115" "DE2i-150"}
set_parameter_property CIV_boards VISIBLE false
set_parameter_property CIV_boards ENABLED true

add_parameter CV_boards string "DE1-SoC"
set_parameter_property CV_boards DISPLAY_NAME "DE-Series Board"
set_parameter_property CV_boards GROUP "Settings"
set_parameter_property CV_boards UNITS None
set_parameter_property CV_boards AFFECTS_ELABORATION true
set_parameter_property CV_boards AFFECTS_GENERATION true
set_parameter_property CV_boards ALLOWED_RANGES {"DE1-SoC"}
set_parameter_property CV_boards VISIBLE true
set_parameter_property CV_boards ENABLED true

#add_parameter SIII_boards string "DE3"
#set_parameter_property SIII_boards DISPLAY_NAME "DE-Series Board"
#set_parameter_property SIII_boards GROUP "Settings"
#set_parameter_property SIII_boards UNITS None
#set_parameter_property SIII_boards AFFECTS_ELABORATION true
#set_parameter_property SIII_boards AFFECTS_GENERATION true
#set_parameter_property SIII_boards ALLOWED_RANGES {"DE3"}
#set_parameter_property SIII_boards VISIBLE false
#set_parameter_property SIII_boards ENABLED true

#add_parameter SIV_boards string "DE4"
#set_parameter_property SIV_boards DISPLAY_NAME "DE-Series Board"
#set_parameter_property SIV_boards GROUP "Settings"
#set_parameter_property SIV_boards UNITS None
#set_parameter_property SIV_boards AFFECTS_ELABORATION true
#set_parameter_property SIV_boards AFFECTS_GENERATION true
#set_parameter_property SIV_boards ALLOWED_RANGES {"DE4"}
#set_parameter_property SIV_boards VISIBLE false
#set_parameter_property SIV_boards ENABLED true

#add_parameter SV_boards string "DE5"
#set_parameter_property SV_boards DISPLAY_NAME "DE-Series Board"
#set_parameter_property SV_boards GROUP "Settings"
#set_parameter_property SV_boards UNITS None
#set_parameter_property SV_boards AFFECTS_ELABORATION true
#set_parameter_property SV_boards AFFECTS_GENERATION true
#set_parameter_property SV_boards ALLOWED_RANGES {"DE5"}
#set_parameter_property SV_boards VISIBLE false
#set_parameter_property SV_boards ENABLED true

add_parameter other_boards string "None"
set_parameter_property other_boards DISPLAY_NAME "DE-Series Board"
set_parameter_property other_boards GROUP "Settings"
set_parameter_property other_boards UNITS None
set_parameter_property other_boards AFFECTS_ELABORATION true
set_parameter_property other_boards AFFECTS_GENERATION true
set_parameter_property other_boards ALLOWED_RANGES {"None"}
set_parameter_property other_boards VISIBLE false
set_parameter_property other_boards ENABLED true

add_parameter board string
set_parameter_property board DISPLAY_NAME "DE-Series Board"
set_parameter_property board GROUP "Settings"
set_parameter_property board UNITS None
set_parameter_property board AFFECTS_ELABORATION true
set_parameter_property board AFFECTS_GENERATION true
#set_parameter_property board ALLOWED_RANGES {"DE0-Nano" DE0 "DE1-SoC" "DE2-115" "DE2i-150"}
set_parameter_property board DERIVED true
set_parameter_property board VISIBLE false
set_parameter_property board ENABLED false

add_parameter device_family string ""
set_parameter_property device_family system_info_type device_family
set_parameter_property device_family VISIBLE false
# | 
# +-----------------------------------


# +-----------------------------------
# | Validation function
# | 
proc validate {} {
	set gui_refclk				[ get_parameter_value "gui_refclk" ]
	set gui_outclk				[ get_parameter_value "gui_outclk" ]
	set CIII_boards			[ get_parameter_value "CIII_boards" ]
	set CIV_boards				[ get_parameter_value "CIV_boards" ]
	set CV_boards				[ get_parameter_value "CV_boards" ]
#	set SIII_boards			[ get_parameter_value "SIII_boards" ]
#	set SIV_boards				[ get_parameter_value "SIV_boards" ]
#	set SV_boards				[ get_parameter_value "SV_boards" ]
	set other_boards			[ get_parameter_value "other_boards" ]
	set board					[ get_parameter_value "board" ]
	set device_family			[ get_parameter_value "device_family" ]
	
	set_parameter_property CIII_boards VISIBLE false
	set_parameter_property CIV_boards VISIBLE false
	set_parameter_property CV_boards VISIBLE false
#	set_parameter_property SIII_boards VISIBLE false
#	set_parameter_property SIV_boards VISIBLE false
#	set_parameter_property SV_boards VISIBLE false
	set_parameter_property other_boards VISIBLE false

	if { [ string match -nocase "Cyclone III*" $device_family ] } {
		set_parameter_property CIII_boards VISIBLE true
		set_parameter_value board $CIII_boards
	} elseif { [ string match -nocase "Cyclone IV*" $device_family ] } {
		set_parameter_property CIV_boards VISIBLE true
		set_parameter_value board $CIV_boards
	} elseif { [ string match -nocase "Cyclone V*" $device_family ] } {
		set_parameter_property CV_boards VISIBLE true
		set_parameter_value board $CV_boards
#	} elseif { [ string match -nocase "Stratix III*" $device_family ] } {
#		set_parameter_property SIII_boards VISIBLE true
#		set_parameter_value board $SIII_boards
#	} elseif { [ string match -nocase "Stratix IV*" $device_family ] } {
#		set_parameter_property SIV_boards VISIBLE true
#		set_parameter_value board $SIV_boards
#	} elseif { [ string match -nocase "Stratix V*" $device_family ] } {
#		set_parameter_property SV_boards VISIBLE true
#		set_parameter_value board $SV_boards
	} else {
		set_parameter_property other_boards VISIBLE true
		set_parameter_value board $other_boards
	}
	
	set_parameter_property gui_refclk VISIBLE false
	set_parameter_property refclk VISIBLE false
	set_parameter_property gui_outclk VISIBLE false
	set_parameter_property outclk VISIBLE false

	if {  [ string match -nocase "Cyclone IV*" $device_family ]  || 
			[ string match -nocase "Cyclone III*" $device_family ] ||
			[ string match -nocase "Arria II*" $device_family ] ||
			[ string match -nocase "Stratix III*" $device_family ] ||
			[ string match -nocase "Stratix IV*" $device_family ]} {
		set_parameter_property refclk VISIBLE true
		set_parameter_property outclk VISIBLE true
		set_parameter_value refclk 50.0
		set_parameter_value outclk 50.0
		
	} else {
		set_parameter_property gui_refclk VISIBLE true
		set_parameter_property gui_outclk VISIBLE true
		set_parameter_value refclk $gui_refclk
		set_parameter_value outclk $gui_outclk
	}
}
# | 
# +-----------------------------------


# +-----------------------------------
# | Composition function
# | 
proc compose {} {
	set refclk				[ get_parameter_value "refclk" ]
	set outclk				[ get_parameter_value "outclk" ]
	set board				[ get_parameter_value "board" ]
	set device_family		[ get_parameter_value "device_family" ]


	# +-----------------------------------
	# | add instances
	# |
	if {  [ string match -nocase "Cyclone IV*" $device_family ]  ||
			[ string match -nocase "Cyclone III*" $device_family ] ||
			[ string match -nocase "Arria II*" $device_family ] ||
			[ string match -nocase "Stratix III*" $device_family ] ||
			[ string match -nocase "Stratix IV*" $device_family ]} {
		add_instance sys_pll altera_up_altpll
		set_instance_property sys_pll SUPPRESS_ALL_INFO_MESSAGES true
		set_instance_property sys_pll SUPPRESS_ALL_WARNINGS true

		set_instance_parameter_value sys_pll type "System/SDRAM"
		
	} else {
		add_instance sys_pll altera_pll
		set_instance_property sys_pll SUPPRESS_ALL_INFO_MESSAGES true
		set_instance_property sys_pll SUPPRESS_ALL_WARNINGS true

		set_instance_parameter_value sys_pll gui_reference_clock_frequency $refclk
		set_instance_parameter_value sys_pll gui_number_of_clocks 2
		set_instance_parameter_value sys_pll gui_output_clock_frequency0 $outclk
		set_instance_parameter_value sys_pll gui_output_clock_frequency1 $outclk
		if { $board == "DE1-SoC" } {
			set_instance_parameter_value sys_pll gui_ps_units1 "degrees"
			set_instance_parameter_value sys_pll gui_phase_shift_deg1  "-90.0"
		} else {
			set_instance_parameter_value sys_pll gui_ps_units1 "ps"
			set_instance_parameter_value sys_pll gui_phase_shift_deg1  "-3000"
		}
	}

	add_instance reset_from_locked altera_up_avalon_reset_from_locked_signal
	# | 
	# +-----------------------------------


	# +-----------------------------------
	# | add connection points
	# | 
	add_interface ref_clk clock end
	add_interface ref_reset reset end
	add_interface sys_clk clock start
	if { $board != "None" } {
		add_interface sdram_clk clock start
	}
	add_interface reset_source reset start
	
	set_interface_property ref_clk EXPORT_OF "sys_pll.refclk"
	set_interface_property ref_reset EXPORT_OF "sys_pll.reset"
	set_interface_property sys_clk EXPORT_OF "sys_pll.outclk0"
	if { $board != "None" } {
		set_interface_property sdram_clk EXPORT_OF "sys_pll.outclk1"
	}
	set_interface_property reset_source EXPORT_OF "reset_from_locked.reset_source"

	add_connection "sys_pll.locked" "reset_from_locked.locked" conduit
	# | 
	# +-----------------------------------
}
# | 
# +-----------------------------------

