# TCL File Generated by Component Editor 15.0
# Sat May 16 12:44:39 EDT 2015
# DO NOT MODIFY


# 
# legup_hps_address_adaptor "LegUp HPS Address Adaptor" v1.0
#  2015.05.16.12:44:39
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module legup_hps_address_adaptor
# 
set_module_property DESCRIPTION ""
set_module_property NAME legup_hps_address_adaptor
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP LegUp/Interconnect/Adapters
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "LegUp HPS Address Adaptor"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL legup_hps_address_adaptor
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file legup_hps_address_adaptor.v VERILOG PATH legup_hps_address_adaptor.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL legup_hps_address_adaptor
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file legup_hps_address_adaptor.v VERILOG PATH legup_hps_address_adaptor.v

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL legup_hps_address_adaptor
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file legup_hps_address_adaptor.v VERILOG PATH legup_hps_address_adaptor.v


# 
# parameters
# 
add_parameter UPPER_BITS INTEGER 0 "address\[31:30] will be set to this value"
set_parameter_property UPPER_BITS DEFAULT_VALUE 0
set_parameter_property UPPER_BITS DISPLAY_NAME UPPER_BITS
set_parameter_property UPPER_BITS WIDTH 2
set_parameter_property UPPER_BITS TYPE INTEGER
set_parameter_property UPPER_BITS UNITS None
set_parameter_property UPPER_BITS ALLOWED_RANGES 0:3
set_parameter_property UPPER_BITS DESCRIPTION "address\[31:30] will be set to this value"
set_parameter_property UPPER_BITS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point bridge
# 
add_interface bridge avalon end
set_interface_property bridge addressUnits SYMBOLS
set_interface_property bridge associatedClock clock
set_interface_property bridge associatedReset reset
set_interface_property bridge bitsPerSymbol 8
set_interface_property bridge burstOnBurstBoundariesOnly false
set_interface_property bridge burstcountUnits WORDS
set_interface_property bridge explicitAddressSpan 0
set_interface_property bridge holdTime 0
set_interface_property bridge linewrapBursts false
set_interface_property bridge maximumPendingReadTransactions 0
set_interface_property bridge maximumPendingWriteTransactions 0
set_interface_property bridge readLatency 0
set_interface_property bridge readWaitTime 1
set_interface_property bridge setupTime 0
set_interface_property bridge timingUnits Cycles
set_interface_property bridge writeWaitTime 0
set_interface_property bridge ENABLED true
set_interface_property bridge EXPORT_OF ""
set_interface_property bridge PORT_NAME_MAP ""
set_interface_property bridge CMSIS_SVD_VARIABLES ""
set_interface_property bridge SVD_ADDRESS_GROUP ""

add_interface_port bridge avs_from_bridge_readdata readdata Output 64
add_interface_port bridge avs_from_bridge_waitrequest waitrequest Output 1
add_interface_port bridge avs_from_bridge_address address Input 32
add_interface_port bridge avs_from_bridge_byteenable byteenable Input 8
add_interface_port bridge avs_from_bridge_read read Input 1
add_interface_port bridge avs_from_bridge_write write Input 1
add_interface_port bridge avs_from_bridge_writedata writedata Input 64
set_interface_assignment bridge embeddedsw.configuration.isFlash 0
set_interface_assignment bridge embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment bridge embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment bridge embeddedsw.configuration.isPrintableDevice 0


# 
# connection point memory
# 
add_interface memory avalon start
set_interface_property memory addressUnits SYMBOLS
set_interface_property memory associatedClock clock
set_interface_property memory associatedReset reset
set_interface_property memory bitsPerSymbol 8
set_interface_property memory burstOnBurstBoundariesOnly false
set_interface_property memory burstcountUnits WORDS
set_interface_property memory doStreamReads false
set_interface_property memory doStreamWrites false
set_interface_property memory holdTime 0
set_interface_property memory linewrapBursts false
set_interface_property memory maximumPendingReadTransactions 0
set_interface_property memory maximumPendingWriteTransactions 0
set_interface_property memory readLatency 0
set_interface_property memory readWaitTime 1
set_interface_property memory setupTime 0
set_interface_property memory timingUnits Cycles
set_interface_property memory writeWaitTime 0
set_interface_property memory ENABLED true
set_interface_property memory EXPORT_OF ""
set_interface_property memory PORT_NAME_MAP ""
set_interface_property memory CMSIS_SVD_VARIABLES ""
set_interface_property memory SVD_ADDRESS_GROUP ""

add_interface_port memory avm_to_memory_readdata readdata Input 64
add_interface_port memory avm_to_memory_waitrequest waitrequest Input 1
add_interface_port memory avm_to_memory_address address Output 32
add_interface_port memory avm_to_memory_byteenable byteenable Output 8
add_interface_port memory avm_to_memory_read read Output 1
add_interface_port memory avm_to_memory_write write Output 1
add_interface_port memory avm_to_memory_writedata writedata Output 64

