#!/bin/bash

# Compile assembly to elf (and sdram.dat) ($1 --> filename.s)
NAME=${1%.*}
OUT_NAME="$NAME"

# Find name so we don't overwrite previously created files
if [ -f $OUT_NAME.elf ]; then
	IDX=1
	while [ -f $OUT_NAME.$IDX.elf ]; do
		let "IDX += 1"
	done
	OUT_NAME="$NAME.$IDX"
fi

MIPS_PREFIX=../../../../mips-binutils/bin/mipsel-elf-
${MIPS_PREFIX}as $NAME.s -mips1 -O0 -mabi=32 -o $OUT_NAME.o -EL
${MIPS_PREFIX}ld -Ttext 0x800000 -e main $OUT_NAME.o -EL -o $OUT_NAME.elf
${MIPS_PREFIX}objdump -Dz $OUT_NAME.elf > $OUT_NAME.src

g++ elf2sdram.cpp -O3 -o elf2sdram
elf2sdram ${OUT_NAME}.elf ${OUT_NAME}.sdram.dat
rm $OUT_NAME.o
rm $OUT_NAME.*dump
