#!/bin/bash

NUM_INSTRS=500	# later can introduce loops

# Instruction Classes
mem_imm="li"		# D = F(S,T)


# Generate Random Number ($1 --> upper bound)
function rand() {
	local number=$RANDOM # $RANDOM returns in range 0..2^8
	let "number %= $1"
	echo "$number"
}


# Compile assembly to elf (and sdram.dat) ($1 --> filename.s)
function assemble() {
	NAME=${1%.*}
	OUT_NAME="$NAME"
	
	# Find name so we don't overwrite previously created files
	if [ -f $OUT_NAME.elf ]; then
		IDX=1
		while [ -f $OUT_NAME.$IDX.elf ]; do
			let "IDX += 1"
		done
		OUT_NAME="$NAME.$IDX"
	fi
	
	MIPS_PREFIX=../../../../mips-binutils/bin/mipsel-elf-
	${MIPS_PREFIX}as $NAME.s -mips1 -O0 -mabi=32 -o $OUT_NAME.o -EL
	${MIPS_PREFIX}ld -Ttext 0x800000 -e main $OUT_NAME.o -EL -o $OUT_NAME.elf
	${MIPS_PREFIX}objdump -Dz $OUT_NAME.elf > $OUT_NAME.src
	
	g++ elf2sdram.cpp -O3 -o elf2sdram
	elf2sdram ${OUT_NAME}.elf ${OUT_NAME}.sdram.dat
	rm $OUT_NAME.o
	rm $OUT_NAME.*dump
}
	
FILE=assembly/lui.li.s
echo -e "\t.text\n\t.globl\tmain\n\t.ent\tmain\nmain:" > $FILE
for i in `seq 1 $NUM_INSTRS`; do	
	RAND1=`rand 1000000`
	echo -e "\tlui \$9, ${RAND1}" >> $FILE
done
echo -e "\tjr \$ra\n\t.end\tmain" >> $FILE
assemble $FILE

# create rest
INSTR_LIST=${mem_imm//,/ }
for op in $(echo $INSTR_LIST); do
	sed "s|lui \$9, |${op} \$9, |g" assembly/lui.li.s > assembly/${op}.li.s
	assemble assembly/${op}.li.s
done

exit