  //Example instantiation for system 'tiger'
  tiger tiger_inst
    (
      .aux_scan_clk_from_the_ddr2            (aux_scan_clk_from_the_ddr2),
      .aux_scan_clk_reset_n_from_the_ddr2    (aux_scan_clk_reset_n_from_the_ddr2),
      .clk                                   (clk),
      .coe_debug_lights_from_the_tiger_top_0 (coe_debug_lights_from_the_tiger_top_0),
      .coe_debug_select_to_the_tiger_top_0   (coe_debug_select_to_the_tiger_top_0),
      .coe_exe_end_from_the_tiger_top_0      (coe_exe_end_from_the_tiger_top_0),
      .coe_exe_start_from_the_tiger_top_0    (coe_exe_start_from_the_tiger_top_0),
      .ddr2_aux_full_rate_clk_out            (ddr2_aux_full_rate_clk_out),
      .ddr2_aux_half_rate_clk_out            (ddr2_aux_half_rate_clk_out),
      .ddr2_phy_clk_out                      (ddr2_phy_clk_out),
      .dll_reference_clk_from_the_ddr2       (dll_reference_clk_from_the_ddr2),
      .dqs_delay_ctrl_export_from_the_ddr2   (dqs_delay_ctrl_export_from_the_ddr2),
      .global_reset_n_to_the_ddr2            (global_reset_n_to_the_ddr2),
      .local_init_done_from_the_ddr2         (local_init_done_from_the_ddr2),
      .local_refresh_ack_from_the_ddr2       (local_refresh_ack_from_the_ddr2),
      .local_wdata_req_from_the_ddr2         (local_wdata_req_from_the_ddr2),
      .mem_addr_from_the_ddr2                (mem_addr_from_the_ddr2),
      .mem_ba_from_the_ddr2                  (mem_ba_from_the_ddr2),
      .mem_cas_n_from_the_ddr2               (mem_cas_n_from_the_ddr2),
      .mem_cke_from_the_ddr2                 (mem_cke_from_the_ddr2),
      .mem_clk_n_to_and_from_the_ddr2        (mem_clk_n_to_and_from_the_ddr2),
      .mem_clk_to_and_from_the_ddr2          (mem_clk_to_and_from_the_ddr2),
      .mem_cs_n_from_the_ddr2                (mem_cs_n_from_the_ddr2),
      .mem_dm_from_the_ddr2                  (mem_dm_from_the_ddr2),
      .mem_dq_to_and_from_the_ddr2           (mem_dq_to_and_from_the_ddr2),
      .mem_dqs_to_and_from_the_ddr2          (mem_dqs_to_and_from_the_ddr2),
      .mem_dqsn_to_and_from_the_ddr2         (mem_dqsn_to_and_from_the_ddr2),
      .mem_odt_from_the_ddr2                 (mem_odt_from_the_ddr2),
      .mem_ras_n_from_the_ddr2               (mem_ras_n_from_the_ddr2),
      .mem_we_n_from_the_ddr2                (mem_we_n_from_the_ddr2),
      .oct_ctl_rs_value_to_the_ddr2          (oct_ctl_rs_value_to_the_ddr2),
      .oct_ctl_rt_value_to_the_ddr2          (oct_ctl_rt_value_to_the_ddr2),
      .reset_n                               (reset_n),
      .reset_phy_clk_n_from_the_ddr2         (reset_phy_clk_n_from_the_ddr2),
      .rxd_to_the_uart_0                     (rxd_to_the_uart_0),
      .txd_from_the_uart_0                   (txd_from_the_uart_0)
    );

