load_lib legup.exp

set expected {# Result:\s+55000\s+}
set hybridexpected {# Result: 55000}

cd ../examples/parallel/openmp/add
set test "add OpenMP"
run-test-hybridparallel-once $test $hybridexpected

set test "add OpenMP_Pure_HW"
run-test-parallel-once $test $expected

cd ../../pthreads/add
set test "add Pthreads"
run-test-hybrid-once $test $hybridexpected

set test "add Pthreads_Pure_HW"
run-test-parallel-once $test $expected

cd ../../../
