load_lib legup.exp

set expected {# Result:\s+60799800\s+}
set hybridexpected {# Result: 60799800}

cd ../examples/parallel/openmp/dotproduct
set test "dotproduct OpenMP"
run-test-hybridparallel-once $test $hybridexpected

set test "dotproduct OpenMP_Pure_HW"
run-test-parallel-once $test $expected

cd ../../pthreads/dotproduct
set test "dotproduct Pthreads"
run-test-hybrid-once $test $hybridexpected

set test "dotproduct Pthreads_Pure_HW"
run-test-parallel-once $test $expected

cd ../../../
