load_lib legup.exp

set expected {# Result:\s+6144\s+}
set hybridexpected {# Result: 6144}

cd ../examples/parallel/openmp/matrixtrans

set test "matrixtrans OpenMP"
run-test-hybridparallel-once $test $hybridexpected

set test "matrixtrans OpenMP_Pure_HW"
run-test-parallel-once $test $expected

cd ../../pthreads/matrixtrans

set test "matrixtrans Pthreads"
run-test-hybrid-once $test $hybridexpected

set test "matrixtrans Pthreads_Pure_HW"
run-test-parallel-once $test $expected

cd ../../../
