load_lib legup.exp

set expected {# Result:\s+24000\s+}
set hybridexpected {# Result: 24000}

cd ../examples/parallel/openmp/perfecthash
set test "perfecthash OpenMP"
run-test-hybridparallel-once $test $hybridexpected

set test "perfecthash OpenMP_Pure_HW"
run-test-parallel-once $test $expected

cd ../../pthreads/perfecthash
set test "perfecthash Pthreads"
run-test-hybrid-once $test $hybridexpected

set test "perfecthash Pthreads_Pure_HW"
run-test-parallel-once $test $expected

cd ../../../
