#
#  Makefile for GXemul src/components/memory
#

CXXFLAGS=$(CWARNINGS) $(COPTIM) $(CPEDANTIC) $(INCLUDE2)
LIBS=$(OTHERLIBS)

OBJS=MemoryMappedComponent.o RAMComponent.o

all: $(OBJS)

$(OBJS): Makefile

clean:
	rm -f $(OBJS)

clean_all: clean
	rm -f Makefile

