# TCL File Generated by University of Toronto's LegUp group
# DO NOT MODIFY

# +-----------------------------------
# | Specify required package(s) 
# | 
package require -exact qsys 13.0
# | 
# +-----------------------------------


# +-----------------------------------
# | module tiger_dcache
# | 
set_module_property DESCRIPTION "Tiger Data Cache"
set_module_property NAME tiger_dcache
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "LegUp/Memory"
set_module_property AUTHOR "University of Cambridge"
set_module_property DISPLAY_NAME "Tiger Data Cache"
#set_module_property DATASHEET_URL "doc/tiger_dcache.pdf"
#set_module_property TOP_LEVEL_HDL_FILE tiger_dcache_av_1port.v
#set_module_property TOP_LEVEL_HDL_MODULE tiger_dcache_av_1port
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property ANALYZE_HDL false
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
# | 
# +-----------------------------------

# +-----------------------------------
# | file sets
# | 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL tiger_dcache_av_1port
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file tiger_dcache.v VERILOG PATH hdl/tiger_dcache.v
add_fileset_file tiger_dcache_av_1port.v VERILOG PATH hdl/tiger_dcache_av_1port.v TOP_LEVEL_FILE
add_fileset_file tiger_dcache_memory.v VERILOG PATH hdl/tiger_dcache_memory.v
add_fileset_file tiger_dcache_parameters.v VERILOG PATH hdl/tiger_dcache_parameters.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL tiger_dcache_av_1port
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file tiger_dcache.v VERILOG PATH hdl/tiger_dcache.v
add_fileset_file tiger_dcache_av_1port.v VERILOG PATH hdl/tiger_dcache_av_1port.v
add_fileset_file tiger_dcache_memory.v VERILOG PATH hdl/tiger_dcache_memory.v
add_fileset_file tiger_dcache_parameters.v VERILOG PATH hdl/tiger_dcache_parameters.v

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL tiger_dcache_av_1port
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file tiger_dcache.v VERILOG PATH hdl/tiger_dcache.v
add_fileset_file tiger_dcache_av_1port.v VERILOG PATH hdl/tiger_dcache_av_1port.v
add_fileset_file tiger_dcache_memory.v VERILOG PATH hdl/tiger_dcache_memory.v
add_fileset_file tiger_dcache_parameters.v VERILOG PATH hdl/tiger_dcache_parameters.v
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point dcache_slave_0
# | 
add_interface dcache_slave_0 avalon end
set_interface_property dcache_slave_0 addressUnits SYMBOLS
set_interface_property dcache_slave_0 associatedClock clock
set_interface_property dcache_slave_0 associatedReset reset
set_interface_property dcache_slave_0 bitsPerSymbol 8
set_interface_property dcache_slave_0 burstOnBurstBoundariesOnly false
set_interface_property dcache_slave_0 burstcountUnits WORDS
set_interface_property dcache_slave_0 explicitAddressSpan 0
set_interface_property dcache_slave_0 holdTime 0
set_interface_property dcache_slave_0 linewrapBursts false
set_interface_property dcache_slave_0 maximumPendingReadTransactions 4
set_interface_property dcache_slave_0 readLatency 0
set_interface_property dcache_slave_0 readWaitTime 1
set_interface_property dcache_slave_0 setupTime 0
set_interface_property dcache_slave_0 timingUnits Cycles
set_interface_property dcache_slave_0 writeWaitTime 0
set_interface_property dcache_slave_0 ENABLED true
set_interface_property dcache_slave_0 EXPORT_OF ""
set_interface_property dcache_slave_0 PORT_NAME_MAP ""
set_interface_property dcache_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port dcache_slave_0 avs_dcache_slave_0_address address Input 31
add_interface_port dcache_slave_0 avs_dcache_slave_0_begintransfer begintransfer Input 1
add_interface_port dcache_slave_0 avs_dcache_slave_0_byteenable byteenable Input 4
add_interface_port dcache_slave_0 avs_dcache_slave_0_read read Input 1
add_interface_port dcache_slave_0 avs_dcache_slave_0_write write Input 1
add_interface_port dcache_slave_0 avs_dcache_slave_0_writedata writedata Input 32
add_interface_port dcache_slave_0 avs_dcache_slave_0_readdata readdata Output 32
add_interface_port dcache_slave_0 avs_dcache_slave_0_readdatavalid readdatavalid Output 1
add_interface_port dcache_slave_0 avs_dcache_slave_0_waitrequest waitrequest Output 1
set_interface_assignment dcache_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment dcache_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment dcache_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment dcache_slave_0 embeddedsw.configuration.isPrintableDevice 0
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point dcache_master_0
# | 
add_interface dcache_master_0 avalon start
set_interface_property dcache_master_0 addressUnits SYMBOLS
set_interface_property dcache_master_0 associatedClock clock
set_interface_property dcache_master_0 associatedReset reset
set_interface_property dcache_master_0 bitsPerSymbol 8
set_interface_property dcache_master_0 burstOnBurstBoundariesOnly false
set_interface_property dcache_master_0 burstcountUnits WORDS
set_interface_property dcache_master_0 doStreamReads false
set_interface_property dcache_master_0 doStreamWrites false
set_interface_property dcache_master_0 holdTime 0
set_interface_property dcache_master_0 linewrapBursts false
set_interface_property dcache_master_0 maximumPendingReadTransactions 0
set_interface_property dcache_master_0 readLatency 0
set_interface_property dcache_master_0 readWaitTime 1
set_interface_property dcache_master_0 setupTime 0
set_interface_property dcache_master_0 timingUnits Cycles
set_interface_property dcache_master_0 writeWaitTime 0
set_interface_property dcache_master_0 ENABLED true
set_interface_property dcache_master_0 EXPORT_OF ""
set_interface_property dcache_master_0 PORT_NAME_MAP ""
set_interface_property dcache_master_0 SVD_ADDRESS_GROUP ""

add_interface_port dcache_master_0 avm_dcache_master_0_readdata readdata Input 32
add_interface_port dcache_master_0 avm_dcache_master_0_readdatavalid readdatavalid Input 1
add_interface_port dcache_master_0 avm_dcache_master_0_waitrequest waitrequest Input 1
add_interface_port dcache_master_0 avm_dcache_master_0_address address Output 32
add_interface_port dcache_master_0 avm_dcache_master_0_beginbursttransfer beginbursttransfer Output 1
add_interface_port dcache_master_0 avm_dcache_master_0_burstcount burstcount Output 3
add_interface_port dcache_master_0 avm_dcache_master_0_byteenable byteenable Output 4
add_interface_port dcache_master_0 avm_dcache_master_0_read read Output 1
add_interface_port dcache_master_0 avm_dcache_master_0_write write Output 1
add_interface_port dcache_master_0 avm_dcache_master_0_writedata writedata Output 32
# | 
# +-----------------------------------
