# TCL File Generated by Component Editor on: 
# Wed Aug 22 11:31:37 BST 2007
# DO NOT MODIFY

set_module_property top_level_hdl_file "vJTAGUart.v"
set_module_property TOP_LEVEL_HDL_MODULE vJTAGUart
set_module_property NAME "vJTAGUart"
set_module_property description ""
set_module_property instantiateInSystemModule true
set_module_property version "1.0"
set_module_property group "JTAG"
set_module_property editable true


# Module parameters

# Clock Interface global_signals_clock
add_interface global_signals_clock clock input 
set_interface_property "global_signals_clock" "externallyDriven" "false"
#set_interface_property "global_signals_clock" "clockRateKnown" "false"
#set_interface_property "global_signals_clock" "clockRate" "0"
# Ports in interface global_signals_clock
add_interface_port global_signals_clock clk clk input 1 
add_interface_port global_signals_clock reset_n reset_n input 1

# Interface controlSlave
add_interface "controlSlave" "avalon" "slave" "global_signals_clock"
set_interface_property "controlSlave" "isNonVolatileStorage" "false"
set_interface_property "controlSlave" "burstOnBurstBoundariesOnly" "false"
set_interface_property "controlSlave" "transparentBridge" "false"
set_interface_property "controlSlave" "readLatency" "0"
set_interface_property "controlSlave" "readWaitStates" "0"
set_interface_property "controlSlave" "isFlash" "false"
set_interface_property "controlSlave" "holdTime" "0"
set_interface_property "controlSlave" "printableDevice" "false"
set_interface_property "controlSlave" "registerIncomingSignals" "false"
set_interface_property "controlSlave" "readWaitTime" "0"
set_interface_property "controlSlave" "setupTime" "0"
set_interface_property "controlSlave" "addressGroup" "0"
set_interface_property "controlSlave" "interleaveBursts" "false"
set_interface_property "controlSlave" "addressAlignment" "NATIVE"
set_interface_property "controlSlave" "isBigEndian" "false"
set_interface_property "controlSlave" "writeLatency" "0"
set_interface_property "controlSlave" "writeWaitTime" "0"
set_interface_property "controlSlave" "timingUnits" "Cycles"
set_interface_property "controlSlave" "minimumUninterruptedRunLength" "1"
set_interface_property "controlSlave" "registerOutgoingSignals" "false"
set_interface_property "controlSlave" "addressSpan" "2"
set_interface_property "controlSlave" "isMemoryDevice" "false"
set_interface_property "controlSlave" "linewrapBursts" "false"
set_interface_property "controlSlave" "alwaysBurstMaxBurst" "false"
set_interface_property "controlSlave" "writeWaitStates" "0"
set_interface_property "controlSlave" "maximumPendingReadTransactions" "0"
set_interface_property "controlSlave" "wellBehavedWaitrequest" "false"
# Ports in interface controlSlave
add_interface_port controlSlave avs_controlSlave_read read input 1
add_interface_port controlSlave avs_controlSlave_write write input 1
add_interface_port controlSlave avs_controlSlave_readdata readdata input 1
add_interface_port controlSlave avs_controlSlave_writedata writedata input 1
add_interface_port controlSlave avs_controlSlave_address address input 1
